CREATE TABLE [dbo].[UsersInRoles]
(
    [UserID] UNIQUEIDENTIFIER NOT NULL, 
    [RoleID] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK_UsersInRoles] PRIMARY KEY ([UserID], [RoleID]), 
    CONSTRAINT [FK_UsersInRoles_ToUser] FOREIGN KEY ([UserID]) REFERENCES [Users]([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_UsersInRoles_ToRole] FOREIGN KEY ([RoleID]) REFERENCES [Roles]([ID])  ON DELETE CASCADE
)
